title: Minghui Qiu's Homepage
page-top-title: Welcome!
top-section-bg-text: Minghui Qiu
home-subtitle: Minghui Qiu&ensp;[míŋxuēɪ tɕiə̄ʊ]&ensp;邱明辉
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
